name: Makefile CI

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make

    - name: Run install
      run: make install

    - name: Run installcheck
      run: make installcheck

      run: make distcheck
